### ISSUE TITLE
Filenames with square brackets give an error

### ISSUE THREAD

**Issue by ymmv99** [mattia72/powershell#1]
The script doesn't work with file names that have square brackets, like 

  "author - [series name] - title.epub".

I've got thousands of files named like  and I'd rather not rename them all just to make the script work. I'd rather have the script work with all possible filenames.

**Comment by mattia72** [comment]
> The script doesn't work ...

Which script do you mean?

**Comment by ymmv99** [comment]
I thought I’d put a remark under the “problematic” script, but I guess from your question that wasn’t the case. I was talking about Get-EpubMetaInfo.ps1

 

(And thanks for your very quick reply!)

 

Saskia

**Comment by mattia72** [comment]
The special charachters in the file name should be escaped:
```powershell
'author - `[series name`] - title.epub'
```
I'll try to find a solution for this problem later. Some ideas are listed here:
https://stackoverflow.com/questions/12090312/how-to-access-file-paths-in-powershell-containing-special-characters

**Comment by mattia72** [comment]
9bcaba8 should solve this.
